home_page/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='hospital-home'),
    path('user/<username>', views.UserNewsView.as_view(), name='user-news'),
    path('news/<int:pk>/', views.NewsDetailsView.as_view(), name='news-detail'),
    path('news/<int:pk>/update/', views.NewsUpdateView.as_view(), name='news-update'),
    path('news/<int:pk>/delete/', views.NewsDeleteView.as_view(), name='news-delete'),
    path('comment/<int:pk>/update/', views.CommentUpdateView.as_view(), name='comment-update'),
    path('comment/<int:pk>/delete/', views.CommentDeleteView.as_view(), name='comment-delete'),
    path('news/new/', views.NewsCreateView.as_view(), name='news-create'),
    path('about/', views.AboutView.as_view(), name='hospital-about'),
]

htmx_urlpatterns = [

]

medic_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from history import views as history_views
from appointment import views as appointment_views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.RegisterView.as_view(), name='register'),
    path('profile/<username>/', user_views.ProfileView.as_view(), name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('records/<username>/',
         history_views.UserMedicalHistoryView.as_view(),
         name='records'),
    path('appointments/', appointment_views.MakeAppointmentView.as_view(), name='create-appointment'),
    path('appointments/<username>/<str:select>', appointment_views.ListAppointmentsView.as_view(),
         name='list-appointment'),
    path('appointments/detail/<username>/<int:pk>', appointment_views.AppointmentDetailView.as_view(),
         name='appointment-detail'),
    path('appointments/treat/<username>/<int:pk>', appointment_views.PatientTreatmentView.as_view(), name='treatment'),
    path('', include('home_page.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



appointment/models.py
from django.db import models
from history.models import IllnessType
from users.models import Profile
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
TIME_CHOICES = (('a', '9:00 - 9:20'),
                ('b', '9:30 - 9:50'),
                ('c', '10:00 - 10:20'),
                ('d', '10:30 - 10:50'),
                ('e', '11:00 - 11:20'),
                ('f', '11:30 - 11:50'),
                ('g', '12:00 - 12:20'),
                ('h', '13:00 - 13:20'),
                ('i', '13:30 - 13:50'),
                ('j', '14:00 - 14:20'),
                ('k', '14:30 - 14:50'),
                ('l', '15:00 - 15:20'),
                ('m', '15:30 - 15:50'),
                ('n', '16:00 - 16:20'),
                ('o', '16:30 - 16:50'),
                ('p', '17:00 - 17:20'))


class Appointment(models.Model):
    patient = models.ForeignKey(User, related_name="patient", on_delete=models.CASCADE)
    type = models.ForeignKey(IllnessType, null=True, on_delete=models.CASCADE)
    doctor = models.ForeignKey(User, null=True, related_name="doctor", on_delete=models.CASCADE)
    date = models.DateField(default=timezone.now)
    time = models.CharField(max_length=1, choices=TIME_CHOICES)
    active = models.BooleanField(default=True)

    class Meta:
        constraints = [models.UniqueConstraint(fields=['patient', 'time', 'date'], name='patient appointment time'),
                       models.UniqueConstraint(fields=['doctor', 'time', 'date'], name='doctor appointment time')]



appointment/forms.py
from django.contrib.auth.models import User
from history.models import IllnessType, Treatment, TYPE_CHOICES
from .models import TIME_CHOICES, Appointment
from django import forms


class AppointmentForm(forms.ModelForm):
    queryset = User.objects.filter(profile__user_type='b')
    doctor = forms.ModelChoiceField(queryset=queryset)
    time = forms.ChoiceField(choices=TIME_CHOICES)
    date = forms.DateField(input_formats=['%d/%m/%Y'], help_text='Format: DD/MM/YYYY')
    type = forms.ModelChoiceField(queryset=IllnessType.objects.all())

    class Meta:
        model = Appointment
        fields = ['doctor', 'type', 'date', 'time']


class TreatmentForm(forms.ModelForm):
    diagnosis = forms.CharField()
    type = forms.ChoiceField(choices=TYPE_CHOICES)
    dose = forms.IntegerField()
    duration = forms.IntegerField()

    class Meta:
        model = Treatment
        fields = ['diagnosis', 'name', 'type', 'dose', 'hospital_name', 'duration']

appointment/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from .forms import AppointmentForm, TreatmentForm
from .models import Appointment
from users.models import Profile
from history.models import MedicalHistoryRecord, Illness
from django.contrib.auth.models import User
from django.http import Http404
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.


class MakeAppointmentView(LoginRequiredMixin, View):
    def get(self, request):
        form = AppointmentForm()
        return render(request, 'create_appointment.html', {'form': form})

    def post(self, request):
        form = AppointmentForm(request.POST)
        if form.is_valid():
            if not Appointment.objects.filter(time=form.cleaned_data.get('time'), date=form.cleaned_data.get('date'),
                                              patient=request.user):
                appointment = form.save(commit=False)
                appointment.patient = request.user
                appointment.save()
                messages.success(request, f'Appointment created!')
                return redirect('list-appointment', request.user.username, 'active')
            messages.error(request, f'An appointment for this time and user already exists!')
        return render(request, 'create_appointment.html', {'form': form})


class AppointmentDetailView(View):
    def get(self, request, username, pk):
        appointment = Appointment.objects.get(pk=pk)
        if not (request.user == appointment.patient or request.user == appointment.doctor):
            messages.error(request, f'Current user is not the correct user!')
            return redirect('hospital-home')
        type = Profile.objects.get(user__username=username).user_type
        if appointment:
            context = {
                'user': User.objects.get(username=username),
                'appointment': appointment,
                'type': type
            }
            return render(request, 'appointment_detail.html', context)
        else:
            raise Http404


class ListAppointmentsView(View):
    def get(self, request, username, select):
        user = User.objects.get(username=username)
        if not request.user == user:
            messages.error(request, f'Current user is not the correct user!')
            return redirect('hospital-home')
        profile = Profile.objects.get(user__username=username)
        if profile.user_type == 'a':
            queryset = Appointment.objects.filter(patient__username=username).order_by('date', 'time').filter(active=True)
            queryset2 = Appointment.objects.filter(patient__username=username).order_by('date', 'time')
        else:
            queryset = Appointment.objects.filter(doctor__username=username).order_by('date', 'time').filter(active=True)
            queryset2 = Appointment.objects.filter(doctor__username=username).order_by('date', 'time')
        context = {
            'user': User.objects.get(username=username),
            'user_type': profile.user_type,
            'appointments': queryset,
            'all': queryset2,
            'select': select
        }
        return render(request, 'user_appointments.html', context)


class PatientTreatmentView(View):
    def get(self, request, username, pk):
        appointment = Appointment.objects.get(pk=pk)
        if not request.user == appointment.doctor:
            messages.error(request, f'Current user is not the correct doctor!')
            return redirect('hospital-home')
        form = TreatmentForm()
        return render(request, 'treatment.html', {'form': form})

    def post(self, request, username, pk):
        form = TreatmentForm(request.POST)
        if form.is_valid():
            treatment = form.save()
            appointment = Appointment.objects.get(pk=pk)
            appointment.active = False
            appointment.save()
            illness = Illness(name=form.cleaned_data.get('diagnosis'), type=appointment.type)
            illness.save()
            record = MedicalHistoryRecord(treatment=treatment, patient= appointment.patient,
                                          illness=illness)
            record.save()
            form.save()
            messages.success(request, f'Treatment Applied!')
            return redirect('list-appointment', username, 'active')
        return render(request, 'treatment.html', {'form': form})

appointment/templates/appointment_detail.html
{% extends "home_page/base.html" %}
{% block content %}
    <title>Hospital - Appointments of {{ user.username }}: Detail</title>
        <h1 class="mb-3">Appointments of {{user.username }}: Detail</h1>
        <a class="mr-2" href="{% url 'list-appointment' user.username 'active' %}">Back to {{ user }}'s Appointments</a>
        <a class="mr-2" href="{% url 'profile' user.username %}"><br>Back to {{ user }}'s Profile</a>
        <table class="table table-striped table-bordered" style="width: 2500px">
        <tr>
            <th>Patient</th>
            <th>Doctor</th>
            <th>Time</th>
            <th>Date</th>
            <th>Illness Type</th>
            <th>Is Active</th>
            {% if type == 'b' %}
                <th>Apply Treatment</th>
            {% endif %}
        </tr>
        <tr>
            <td><a class="mr-2" href="{% url 'profile' appointment.patient.username %}">{{ appointment.patient }}</a></td>
            <td><a class="mr-2" href="{% url 'profile' appointment.doctor.username %}">{{ appointment.doctor }}</a></td>
            <td>{{ appointment.get_time_display }}</td>
            <td>{{ appointment.date }}</td>
            <td>{{ appointment.type }}</td>
            {% if appointment.active %}
                <td>Yes</td>
            {% else %}
                <td>No</td>
            {% endif %}
            {% if type == 'b' %}
                <th><a class="btn btn-outline-info btn-sm mt-1 mb-1" href="{% url 'treatment' user.username appointment.pk %}">Apply Treatment</a></th>
            {% endif %}
        </tr>
        </table>

{% endblock content %}

appointment/templates/create_appointment.html
{% extends "home_page/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <title>Hospital - Create Appointment</title>
    <div class="content-section">
        <form action="" method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Appointment</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Submit</button>
            </div>
        </form>
    </div>
{% endblock content %}

appointment/templates/treatment.html
{% extends "home_page/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <title>Hospital - Apply Treatment</title>
    <div class="content-section">
        <form action="" method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Apply Treatment</legend>
                {{ form|crispy  }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Submit</button>
            </div>
        </form>
    </div>
{% endblock content %}

appointment/templates/user_appointments.html
{% extends "home_page/base.html" %}
{% block content %}
    <title>Hospital - Appointments of {{ user.username }}</title>
        <h1 class="mb-3">Appointments of {{user.username }}</h1>
        <a class="mr-2" href="{% url 'profile' user.username %}">Back to {{ user }}'s Profile</a>
        {% if select == 'active' %}
            <a class="mr-2" href="{% url 'list-appointment' user.username 'all' %}"><br>Show All Appointments</a>
        {% elif select == 'all' %}
            <a class="mr-2" href="{% url 'list-appointment' user.username 'active' %}"><br>Show Only Active Appointments</a>
        {% endif %}
        <table class="table table-striped table-bordered" style="width: 2500px">
        <tr>
            <th>Patient</th>
            <th>Doctor</th>
            <th>Time</th>
            <th>Date</th>
            <th>Illness Type</th>
            <th>Is Active</th>
            <th>Details</th>
        </tr>
        {% if select == 'active' %}
            {% for appointment in appointments %}
                <tr>
                    <td><a class="mr-2" href="{% url 'profile' appointment.patient.username %}">{{ appointment.patient }}</a></td>
                    <td><a class="mr-2" href="{% url 'profile' appointment.doctor.username %}">{{ appointment.doctor }}</a></td>
                    <td>{{ appointment.get_time_display }}</td>
                    <td>{{ appointment.date }}</td>
                    <td>{{ appointment.type }}</td>
                    {% if appointment.active %}
                        <td>Yes</td>
                    {% else %}
                        <td>No</td>
                    {% endif %}
                    <td><a class="btn btn-outline-info btn-sm mt-1 mb-1" href="{% url 'appointment-detail' user.username appointment.pk %}">Details</a></td>
                </tr>
            {% endfor %}

        {% elif select == 'all' %}
            {% for appointment in all %}
                <tr>
                    <td><a class="mr-2" href="{% url 'profile' appointment.patient.username %}">{{ appointment.patient }}</a></td>
                    <td><a class="mr-2" href="{% url 'profile' appointment.doctor.username %}">{{ appointment.doctor }}</a></td>
                    <td>{{ appointment.get_time_display }}</td>
                    <td>{{ appointment.date }}</td>
                    <td>{{ appointment.type }}</td>
                    {% if appointment.active %}
                        <td>Yes</td>
                    {% else %}
                        <td>No</td>
                    {% endif %}
                    <td><a class="btn btn-outline-info btn-sm mt-1 mb-1" href="{% url 'appointment-detail' user.username appointment.pk %}">Details</a></td>
                </tr>
            {% endfor %}
        {% endif %}
        </table>

{% endblock content %}