home_page/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='hospital-home'),
    path('user/<username>', views.UserNewsView.as_view(), name='user-news'),
    path('news/<int:pk>/', views.NewsDetailsView.as_view(), name='news-detail'),
    path('news/<int:pk>/update/', views.NewsUpdateView.as_view(), name='news-update'),
    path('news/<int:pk>/delete/', views.NewsDeleteView.as_view(), name='news-delete'),
    path('comment/<int:pk>/update/', views.CommentUpdateView.as_view(), name='comment-update'),
    path('comment/<int:pk>/delete/', views.CommentDeleteView.as_view(), name='comment-delete'),
    path('news/new/', views.NewsCreateView.as_view(), name='news-create'),
    path('about/', views.AboutView.as_view(), name='hospital-about'),
]

htmx_urlpatterns = [

]

medic_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from history import views as history_views
from appointment import views as appointment_views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.RegisterView.as_view(), name='register'),
    path('profile/<username>/', user_views.ProfileView.as_view(), name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('records/<username>/',
         history_views.UserMedicalHistoryView.as_view(),
         name='records'),
    path('appointments/', appointment_views.MakeAppointmentView.as_view(), name='create-appointment'),
    path('appointments/<username>/<str:select>', appointment_views.ListAppointmentsView.as_view(),
         name='list-appointment'),
    path('appointments/detail/<username>/<int:pk>', appointment_views.AppointmentDetailView.as_view(),
         name='appointment-detail'),
    path('appointments/treat/<username>/<int:pk>', appointment_views.PatientTreatmentView.as_view(), name='treatment'),
    path('', include('home_page.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



users/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User
from PIL import Image

# Create your models here.
CHOICES = (('a', 'Patient'),
           ('b', 'Doctor'))


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='blank-profile-picture.png', upload_to='profile_pics')
    user_type = models.CharField(max_length=1, choices=CHOICES, default='a')

    def __str__(self):
        return f'Profile of {self.user.username}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile, CHOICES


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    user_type = forms.ChoiceField(choices=CHOICES)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'user_type']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

users/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from .models import Profile
from django.contrib.auth.models import User
from home_page.models import News


class RegisterView(View):
    def get(self, request):
        form = UserRegisterForm()
        return render(request, 'users/register.html', {'form': form})

    def post(self, request):
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.profile.user_type = form.cleaned_data.get('user_type')
            Profile.objects.update_or_create(user=user)
            user.save()
            messages.success(request, f'Account created!')
            return redirect('login')
        return render(request, 'users/register.html', {'form': form})


class ProfileView(View):
    def get(self, request, username):
        user = User.objects.get(username=username)
        profile = Profile.objects.get(user=user)
        news = News.objects.filter(author=user)
        u_form = UserUpdateForm(instance=user)
        p_form = ProfileUpdateForm(instance=user)
        context = {
            'u_form': u_form,
            'p_form': p_form,
            'title': f'Profile of {user.username}',
            'profile_user': user,
            'news': news,
            'profile': profile
        }
        return render(request, 'users/profile.html', context)

    def post(self, request, username):
        user = User.objects.get(username=username)
        u_form = UserUpdateForm(request.POST, instance=user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Account updated.')
            return redirect('profile', username=user.username)
        context = {
            'u_form': u_form,
            'p_form': p_form
        }
        return render(request, 'users/profile.html', context)

users/templates/users/login.html
{% extends "home_page/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <title>Hospital - Login</title>
    <div class="content-section">
        <form action="" method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy  }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need an account? <a href="{% url 'register' %}" class="ml-2">Sign up</a>
            </small>
        </div>
    </div>
{% endblock content %}

users/templates/users/logout.html
{% extends "home_page/base.html" %}
{% block content %}
    <title>Hospital - Logout</title>
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'login' %}">Log in again</a>
        </small>
    </div>
{% endblock content %}

users/templates/users/profile.html
{% extends "home_page/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <title>Hospital - Profile of {{ profile_user.username }}</title>
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ profile_user.profile.image.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ profile_user.username }}</h2>
          <p class="text-secondary">{{ profile_user.email }}</p>
          <p class="text-secondary">{{ profile.get_user_type_display }}</p>
          <a class="mr-2" href="{% url 'user-news' profile_user.username%}">{{ profile_user }}'s News</a>
          {% if user.is_authenticated %}
              {% if profile_user == user%}
                <a class="mr-2" href="{% url 'list-appointment' profile_user.username 'active'%}"><br>{{ profile_user }}'s Appointments</a>
                  {% if profile.user_type == 'a' %}
                      <a class="mr-2" href="{% url 'records' profile_user.username%}"><br>{{ profile_user }}'s Medical Record</a>
                      <div>
                          <a class="btn btn-outline-info btn-sm mt-1 mb-1" href="{% url 'create-appointment' %}">Make an appointment</a>
                      </div>
                  {% endif %}
              {% endif %}
          {% endif %}
        </div>
      </div>
      {% if user.is_authenticated %}
          {% if profile_user == user %}
              <form action="" method="POST" enctype="multipart/form-data">
                  {% csrf_token %}
                  <fieldset class="form-group">
                      <legend class="border-bottom mb-4">Profile Info</legend>
                      {{ u_form|crispy  }}
                      {{ p_form|crispy  }}
                  </fieldset>
                  <div class="form-group">
                      <button class="btn btn-outline-info" type="submit">Update</button>
                  </div>
              </form>
          {% endif %}
      {% endif %}
    </div>
{% endblock content %}

users/templates/users/register.html
{% extends "home_page/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <title>Hospital - Register Here</title>
    <div class="content-section">
        <form action="" method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Register Here</legend>
                {{ form|crispy  }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already have an account? <a href="{% url 'login' %}" class="ml-2">Sign in</a>
            </small>
        </div>
    </div>
{% endblock content %}